services:
  account-service:
    build:
      context: .
    container_name: account-service
    environment:
      ZIPKIN_ENDPOINT: http://host.docker.internal:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_DEFAULT_ZONE: http://host.docker.internal:8761/eureka/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8081"
